version: '3.9'

services:
  db:
    image: mcr.microsoft.com/mssql/server:2022-latest
    container_name: sqlserver
    environment:
      SA_PASSWORD: "YourStrong@Passw0rd"
      ACCEPT_EULA: "Y"
    ports:
      - "1433:1433"
    volumes:
      - mssql_data:/var/opt/mssql
    networks:
      - app-network

  backend:
    build:
      context: ./backend/UserManagement
      dockerfile: UserManagement.API/Dockerfile
    command: ["dotnet", "UserManagement.API.dll", "migrate"]
    depends_on:
      - db
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ConnectionStrings__DefaultConnection=Server=db;Database=UserDb;User Id=sa;Password=YourStrong@Passw0rd;Encrypt=False;
    ports:
      - "7020:8080"
      - "7021:8081"
    networks:
      - app-network

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    ports:
      - "4200:80"
    depends_on:
      - backend
    networks:
      - app-network

volumes:
  mssql_data:

networks:
  app-network:

